server:
  servlet:
    context-path: /bakery-user-service/api

db:
  host: ${DB_HOST}
  port: ${DB_PORT:5432}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    user: ${db.username}
    password: ${db.password}

allowed:
  urls:
    - ${ALLOWED_ORIGIN:https://your-frontend-domain.com}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
