server:
  servlet:
    context-path: /bakery-user-service/api
  port: 8081

db:
  host: ${DB_HOST}
  port: ${DB_PORT:5432}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

app:
  clients:
    googleUserInfo:
      url: https://www.googleapis.com
    googleOauth2Api:
      url: https://oauth2.googleapis.com

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

  security:
    oauth2:
      client:
        registration:
          google:
            url: ${GOOGLE_OAUTH2_URL}
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope: profile email
            redirect-uri: ${GOOGLE_OAUTH2_REDIRECT_URL}

flyway:
  enabled: true
  baseline-on-migrate: true
  schemas: public
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
  user: ${db.username}
  password: ${db.password}

allowed:
  urls: ${ALLOWED_ORIGIN:https://your-frontend-domain.com}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
