name: Build and Test On PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write  # Required for authentication

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        env:
          M22: ${{ secrets.M2 }}
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
        run: echo "M22 is $MM22"

      - name: Build with Maven
        run: mvn clean install --batch-mode

#        - name: Run tests with Maven
#          run: mvn clean install