name: Build and Test On PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write  # Required for authentication

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven settings for GitHub Packages
        run: |
          echo "<servers>" >> ~/.m2/settings.xml
          echo "  <server>" >> ~/.m2/settings.xml
          echo "    <id>github</id>" >> ~/.m2/settings.xml
          echo "    <username>${{ github.actor }}</username>" >> ~/.m2/settings.xml
          echo "    <password>${{ secrets.GITHUB_TOKEN }}</password>" >> ~/.m2/settings.xml
          echo "  </server>" >> ~/.m2/settings.xml
          echo "</servers>" >> ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean install --batch-mode

#        - name: Run tests with Maven
#          run: mvn clean install